In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 10 dòng đầu
df = pd.read_csv('/content/sample_data/dulieuxettuyendaihoc.csv')
df.head(10)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A
5,6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,...,5.7,8.0,7.8,M,NaN,1,1.50,4.00,6.00,D1
6,7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,...,6.6,6.0,6.0,F,NaN,2,6.50,6.75,5.25,C
7,8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,...,7.1,6.8,7.0,F,NaN,2,3.75,4.50,4.25,D1
8,9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,...,9.1,7.9,6.1,F,NaN,1,3.50,3.50,6.75,D1
9,10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,...,6.4,6.1,7.8,F,NaN,1,4.00,4.75,5.50,D1

In [1]:
# 10 dòng cuối
df.tail(10)

NameError: name 'df' is not defined

In [ ]:
#Thay thế dữ liệu thiếu
df['DT'].fillna(0, inplace=True)
df

/tmp/ipykernel_572/2025981867.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DT'].fillna(0, inplace=True)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [ ]:
# xử lý lần lượt tất cả dữ liệu thiếu cho các biến về điểm số còn lại
cac_bien_con_lai = [
    'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1',
    'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2',
    'T6', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6',
    'DH1', 'DH2', 'DH3'
]
for col in cac_bien_con_lai:
    df[col].fillna(df[col].mean(), inplace=True)
    df

/tmp/ipykernel_572/1654356762.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [ ]:
#Tạo các biến TBM1, TBM2, TBM3 tương ứng với trung bình môn của các năm lớp 10, 11 và
12.
df['TBM1'] = (df['T1']*2 + df['L1'] + df['H1'] + df['S1'] + df['V1']*2 + df['X1'] + df['D1'] + df['N1']) / 10
df['TBM2'] = (df['T2']*2 + df['L2'] + df['H2'] + df['S2'] + df['V2']*2 + df['X2'] + df['D2'] + df['N2']) / 10
df['TBM3'] = (df['T6']*2 + df['L6'] + df['H6'] + df['S6'] + df['V6']*2 + df['X6'] + df['D6'] + df['N6']) / 10

print(df[['TBM1', 'TBM2', 'TBM3']])

    TBM1  TBM2  TBM3
0   7.00  7.54  7.01
1   4.69  5.47  5.07
2   5.77  5.38  6.04
3   6.21  5.20  6.88
4   6.50  6.36  6.99
..   ...   ...   ...
95  7.43  7.42  6.83
96  4.93  5.15  6.39
97  7.05  7.84  7.67
98  4.15  4.72  5.29
99  5.26  5.72  5.85

[100 rows x 3 columns]

In [ ]:
#Tạo các biến xếp loại XL1, XL2 và XL3 dựa trên TBM1,TBM2 và TBM3
def phan_loai_hoc_luc(diem):
    if diem >= 9:
        return 'Xuất Sắc'
    elif diem >= 8:
        return 'Giỏi'
    elif diem >= 7:
        return 'Khá'
    elif diem >= 5:
        return 'Trung Bình'
    else:
        return 'Yếu'

df["XL1"] = df["TBM1"].apply(phan_loai_hoc_luc)
df["XL2"] = df["TBM2"].apply(phan_loai_hoc_luc)
df["XL3"] = df["TBM3"].apply(phan_loai_hoc_luc)


df

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,DH1,DH2,DH3,KT,TBM1,TBM2,TBM3,XL1,XL2,XL3
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,3.25,3.25,4.50,A1,7.00,7.54,7.01,Khá,Khá,Khá
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.00,4.00,3.50,C,4.69,5.47,5.07,Yếu,Trung Bình,Trung Bình
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.00,6.75,4.00,C,5.77,5.38,6.04,Trung Bình,Trung Bình,Trung Bình
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,4.25,4.25,5.25,D1,6.21,5.20,6.88,Trung Bình,Trung Bình,Trung Bình
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,4.25,4.50,5.00,A,6.50,6.36,6.99,Trung Bình,Trung Bình,Trung Bình
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,5.25,1.50,6.25,C,7.43,7.42,6.83,Khá,Khá,Trung Bình
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,5.25,3.75,4.75,C,4.93,5.15,6.39,Yếu,Trung Bình,Trung Bình
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,7.00,8.00,4.00,C,7.05,7.84,7.67,Khá,Khá,Khá
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,5.00,3.50,5.50,C,4.15,4.72,5.29,Yếu,Yếu,Trung Bình
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.25,2.50,4.25,C,5.26,5.72,5.85,Trung Bình,Trung Bình,Trung Bình

In [ ]:
#Tạo các biến US_TBM1, US_TBM2 và US_TBM3
df['US_TBM1'] = (df['TBM1'] / 10) * 4
df['US_TBM2'] = (df['TBM2'] / 10) * 4
df['US_TBM3'] = (df['TBM3'] / 10) * 4
df

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,KT,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,A1,7.00,7.54,7.01,Khá,Khá,Khá,2.800,3.016,2.804
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,C,4.69,5.47,5.07,Yếu,Trung Bình,Trung Bình,1.876,2.188,2.028
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,C,5.77,5.38,6.04,Trung Bình,Trung Bình,Trung Bình,2.308,2.152,2.416
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,D1,6.21,5.20,6.88,Trung Bình,Trung Bình,Trung Bình,2.484,2.080,2.752
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,A,6.50,6.36,6.99,Trung Bình,Trung Bình,Trung Bình,2.600,2.544,2.796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,C,7.43,7.42,6.83,Khá,Khá,Trung Bình,2.972,2.968,2.732
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,C,4.93,5.15,6.39,Yếu,Trung Bình,Trung Bình,1.972,2.060,2.556
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,C,7.05,7.84,7.67,Khá,Khá,Khá,2.820,3.136,3.068
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,C,4.15,4.72,5.29,Yếu,Yếu,Trung Bình,1.660,1.888,2.116
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,C,5.26,5.72,5.85,Trung Bình,Trung Bình,Trung Bình,2.104,2.288,2.340

In [ ]:
#Tạo biến kết quả xét tuyển (kí hiệu là KQXT) nhằm xác định sinh viên đậu (giá trị “1”) và rớt ( giá trị “0”) vào các khối dựa trên điểm DH1, DH2 và DH3
def ket_qua_xet_tuyen(du_lieu):
  khoi_thi =du_lieu['KT']
  dh1 = du_lieu['DH1']
  dh2 = du_lieu['DH2']
  dh3 = du_lieu['DH3']



  if khoi_thi in ['A','A1']:
    diem_xt = (dh1 * 2 + dh2 + dh3)/4
  elif khoi_thi in ['B','B1']:
      diem_xt = (dh1 + dh2*2 + dh3)/4
  else:
      diem_xt = (dh1 + dh2 + dh3*2) / 3

  if diem_xt >= 5.0:
      return 1
  else:
      return 0

df['KQXT'] = df.apply(ket_qua_xet_tuyen, axis=1)
df

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,7.00,7.54,7.01,Khá,Khá,Khá,2.800,3.016,2.804,0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,4.69,5.47,5.07,Yếu,Trung Bình,Trung Bình,1.876,2.188,2.028,1
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.77,5.38,6.04,Trung Bình,Trung Bình,Trung Bình,2.308,2.152,2.416,1
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,6.21,5.20,6.88,Trung Bình,Trung Bình,Trung Bình,2.484,2.080,2.752,1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.50,6.36,6.99,Trung Bình,Trung Bình,Trung Bình,2.600,2.544,2.796,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,7.43,7.42,6.83,Khá,Khá,Trung Bình,2.972,2.968,2.732,1
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,4.93,5.15,6.39,Yếu,Trung Bình,Trung Bình,1.972,2.060,2.556,1
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,7.05,7.84,7.67,Khá,Khá,Khá,2.820,3.136,3.068,1
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,4.15,4.72,5.29,Yếu,Yếu,Trung Bình,1.660,1.888,2.116,1
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.26,5.72,5.85,Trung Bình,Trung Bình,Trung Bình,2.104,2.288,2.340,1